addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    - jacoco.exec
    target_paths: acc56386-faca-4f6b-afe3-5df1de8399d7
after_success:
- ' wget --content-disposition http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.7.201606060606/jacoco-0.7.7.201606060606.zip '
- ' unzip -o jacoco-0.7.7.201606060606.zip  '
- ' cd lib  '
- ' mv * ../  '
- ' cd ..  '
- ' chmod a+x *  '
- ' cd $PWD  '
- ' rm  ''jacoco.exec'''
- ' export JAVA_TOOL_OPTIONS=-javaagent:$PWD/jacocoagent.jar=destfile=$PWD/jacoco.exec,append=true  '
- ' travis_wait 720 mvn  test -Dmaven.test.failure.ignore=true -Djacoco.skip=true
  -Dcobertura.skip=true -Dmaven.clover.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true
  -Drat.ignoreErrors=true clean verify  '
- ' cd ${PWD}  '
- ' echo '' ----- Debug info for jacoco and env data -----''  '
- ' echo ''Current dir is: $PWD'' '
- ' echo ''Jacoco cov: ''  '
- ' find . -name ''*.exec''  '
- ' echo '' ----------------------------------------------'' '
- ./df-build.sh
before_install:
- git config --global user.name "Goodow Bot"
- git config --global user.email "dev@goodow.com"
- cd bower-realtime-store && git pull origin gh-pages && git remote set-url origin
  "https://${GH_TOKEN}@github.com/goodow/bower-realtime-store.git"
- cd ${TRAVIS_BUILD_DIR}
- wget -P target/travis https://raw.githubusercontent.com/goodow/maven/master/settings.xml
- curl http://packages.elasticsearch.org/GPG-KEY-elasticsearch | sudo apt-key add
  -
- echo "deb http://packages.elasticsearch.org/elasticsearch/1.4/debian stable main"
  | sudo tee -a /etc/apt/sources.list
- sudo apt-get update -qq
- sudo apt-get install elasticsearch && sudo service elasticsearch start
branches: ''
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - secure: GKYojWRCCHigM4YaccAnRjHJMm/POM615suzeNX3/Bt4y2wh9gaOvboZs4ybjtQ0TUF+OVQOI3gETqDB+HvF9qsW8LmpRu5Eo05xoDkvtWFkZOd1JOTHwGlmAHYXLoINHHB6o4KgK62BNeUvxGI/anLh+IgZzXKJKZGdz1yJd+s=
jdk:
- oraclejdk8
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-dev.public-swarm.devfactory.com/travisWebHookListener?build_id=acc56386-faca-4f6b-afe3-5df1de8399d7
script:
- mvn test -B
- ./gwt-compile.sh
services:
- redis-server
# Modified by Insights Service at 2016-11-27 19:04:36.945861
